### ISSUE TITLE
Errors when running 4D content generation demo

### ISSUE THREAD

**Issue by Colezwhy** [aejion/4Diffusion#2]
![image](https://github.com/aejion/4Diffusion/assets/96565109/6bf65b92-670e-4710-8158-ccf3622f4908)
Good job, but when I am running the multi-view video generation demo, I met the error message above, would you please have some suggestions on this?

**Comment by aejion** [comment]
You can try adding export CUDA_VISIBLE_DEVICES=x at the top of demo.sh, where x denotes the ID of the GPU you want to use.

**Comment by Colezwhy** [comment]
> You can try adding export CUDA_VISIBLE_DEVICES=x at the top of demo.sh, where x denotes the ID of the GPU you want to use.

Thank you, I will try it.
